background = #111113
foreground = #e0e0e0
cursor-color = #668fff
cursor-text = #111113
selection-background = #668fff
selection-foreground = #111113
palette = 0=#111113
palette = 1=#e06c75
palette = 2=#98c379
palette = 3=#e5c07b
palette = 4=#668fff
palette = 5=#c678dd
palette = 6=#56b6c2
palette = 7=#abb2bf
palette = 8=#5c6370
palette = 9=#e06c75
palette = 10=#98c379
palette = 11=#e5c07b
palette = 12=#668fff
palette = 13=#c678dd
palette = 14=#56b6c2
palette = 15=#f0f0f0
